# Generated by Django 4.1.7 on 2023-04-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='Instructions',
            field=models.CharField(max_length=5000),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('DayId', models.AutoField(primary_key=True, serialize=False)),
                ('DayName', models.CharField(max_length=100)),
                ('DayExercises', models.ManyToManyField(to='WorkoutAPI.exercises')),
            ],
        ),
        migrations.AddField(
            model_name='routines',
            name='RoutineDays',
            field=models.ManyToManyField(to='WorkoutAPI.day'),
        ),
    ]
