# Generated by Django 4.1.7 on 2023-04-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutAPI', '0002_alter_exercises_instructions_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='DayExercises',
            field=models.ManyToManyField(blank=True, to='WorkoutAPI.exercises'),
        ),
    ]
