# Generated by Django 4.1.7 on 2023-05-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutAPI', '0003_alter_day_dayexercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('RoutineId', models.AutoField(primary_key=True, serialize=False)),
                ('RoutineName', models.CharField(max_length=100)),
                ('RoutineDays', models.ManyToManyField(blank=True, to='WorkoutAPI.day')),
            ],
        ),
        migrations.DeleteModel(
            name='Routines',
        ),
    ]
